version: '3'
services:
  redis:
    image: 'redis:5-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    restart: always
  # to visit redis via cli
  # > docker-compose up -d
  # > docker-compose run redis-cli
  # > auth 'your-redis-password'
  # > info
  # > exit 
  redis-cli:
    image: 'redis:5-alpine'
    links:
      - redis
    command: redis-cli -h redis
  db:
    image: 'postgres:11-alpine'
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  # to visit psql
  # > docker-compose up -d
  # you have to wait for a while before executing psql (maybe 30 sec),
  # because postgres hasn't completed initializaztion yet.
  # > docker-compose run psql
  # > SELECT 1;
  # > exit
  psql:
    image: 'postgres:11-alpine'
    links:
      - db
    command: psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB}
