version: '3'
services:
  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
  # after docker-compose up, exec docker-compose run redis-cli,
  # and run auth 'your-redis-password' to access redis-cli 
  redis-cli:
    image: 'redis:4-alpine'
    links:
      - redis
    command: redis-cli -h redis

